- README.md
- cmd/root.go
- gdu.1
It confused me that no-progress didn't work in the interactive mode. After reading the source code, I realized that it only works in non-interactive mode. This makes sense because it seems that no-progress is useful only when its output is used in a script. So I believe this is not a bug but the help text needs to mention this.
> docs: no-progress only works in non-interactive mode

- tui/keys.go
Quick hack to keep the cursor on place when toggling actual/apparent size. Not sure this is the ideal place to do this as I'm completely unfamiliar with tview, but just thought I'd share. Thanks for this great little app.
> Keep cursor on selection when swapping between apparent/actual size.

- cmd/app/app_test.go
TestMaxCoreHighEdge and TestMaxCoreLowEdge tests fail on single core CPUs.
Signed-off-by: Leonidas Spyropoulos <artafinde@gmail.com>
> Skip failing tests on single core CPUs

- tui/actions.go
- tui/filter.go
- tui/filter_test.go
- tui/keys.go
- tui/tui.go
- tui/tui_test.go
> search items by name

- tui/exec_other.go
- tui/exec_windows.go
- tui/keys.go
- tui/shell_other.go
- tui/shell_windows.go
- tui/tui.go
This PR abstracts the `ui.exec` method away into a separate function, which fixes three things:
When `SHELL` is set to `/usr/bin/pwsh`, gdu threw this error on pressing <kbd>b</kbd>:
```
terminate called after throwing an instance of 'std::bad_alloc'
what():  std::bad_alloc
```
This has been fixed, and PowerShell now spawns correctly in the current directory.
Pressing <kbd>b</kbd> didn't work if `SHELL` was Zsh or PowerShell; it only worked on Bash.
_zsh_
```
zsh: too few arguments
```
_pwsh_
```
libc++abi.dylib: terminating with uncaught exception of type std::length_error: vector
```
This has been fixed; any shell works now.
The system call `Exec` does not exist on Windows. A workaround is to spawn a new process and give the input/output/error descriptors of gdu to that process. …
> Shell fixes

- tui/keys.go
Pressing "i" when info modal is open will now close the info modal. Note that this block of code would only work when placed before what is now the block at lines 57-72, it would not work after that.
> Info modal closes with "i"

- pkg/device/dev_darwin.go
- pkg/device/dev_darwin_test.go
- pkg/device/dev_other.go
The output of `/sbin/mount` is pretty similar to FreeBSD one. Since its
very common to have spaces in paths we handle mount points with spaces
as well.
Fixes:  #107
> Implement noCross for darwin

- tui/tui.go
Fixes #124
As a side effect also fixes the hard link information in the "info"
screen after a rescan.
> Properly count only the first hard link size on a rescan

- stdout/stdout.go
- stdout/stdout_test.go
Before this change, gdu produces different output for `gdu -nps` and
`gdu -p -o- | gdu -nps -f-`.
Check ui.summarize in ReadAnalysis, similar to AnalyzePath.
> fix: honor --summarize when reading analysis

- README.md
- cmd/gdu/app/app.go
- cmd/gdu/app/app_test.go
- tui/tui.go
> feat: added possibility to change color of the selected text

- README.md
- cmd/gdu/app/app.go
- cmd/gdu/app/app_test.go
- tui/sort.go
- tui/sort_test.go
- tui/tui.go
> feat: set default sorting using config option

- Makefile
On macOS `tar` doesn't support the `--transform` flag, but one can install the GNU version of it via `brew install gnu-tar` and call it via `gtar`. So all I did was to replace `tar` with `gtar` on macOS. 
I'm not sure if this is a good solution as it involves installation of external dependency and having Homebrew installed as well. Perhaps a better fix would be to create a `$(NAMEVER)` directory, copy binaries there and tar that directory instead for maximum cross-compatibility.
> Use GNU tar on Darwin to fix build error

- tui/mouse.go
- tui/mouse_test.go
> fix: ignore mouse events when modal is opened

- README.md
- cmd/gdu/app/app.go
- cmd/gdu/app/app_test.go
- cmd/gdu/main.go
- internal/common/analyze.go
- internal/common/ui.go
- internal/common/ui_test.go
- internal/testanalyze/analyze.go
- pkg/analyze/dir.go
- pkg/analyze/dir_test.go
- tui/tui.go
> feat: added option to follow symlinks

- .github/dependabot.yml
- .github/workflows/winget.yml
- README.md
[This action](https://github.com/vedantmgoyal2009/winget-releaser) automatically generates manifests for Winget Community Repository ([microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs)) and submits them.
gdu is available in Winget ([![winget package](https://repology.org/badge/version-for-repo/winget/gdu.svg)](https://repology.org/project/gdu/versions)) but is outdated. I have manually created a PR to update it for now (https://github.com/microsoft/winget-pkgs/pull/96456), but this workflow should automatically keep it up to date for the new versions.
**Before merging this:**
1. Add a **classic** PAT with `public_repo` scope as a repository secret named `WINGET_TOKEN`.
2. Fork https://github.com/microsoft/winget-pkgs under @dundee. The action will use that fork for making a …
> ci: Add Winget Releaser workflow

- README.md
The previous link was referencing the AUR package which no longer exists
> Fix link to Arch Linux package

- README.md
- cmd/gdu/app/app.go
- cmd/gdu/app/app_test.go
- tui/actions_test.go
- tui/show.go
- tui/tui.go
tried to implement #229 always (try to) change directory
> implement #229 always (try to) change directory

- tui/keys.go
only tested on
- OS:
- ubuntu 22.04
- terminal: 
- terminator
- kitty
- TERM
- xterm-*
- linux //scroll back maybe broken (same as vim)
> feat: add ctrl+z for job control

- README.md
Add installation option via Scoop for Windows (originally added as ScoopInstaller/Main#2311).
> docs: add Scoop installation note

- README.md
Follow-up of https://github.com/dundee/gdu/issues/48#issuecomment-1604226714
After installing I can confirm that `gdu` doesn't run the program, but `gdu-go` does.
> Fix instructions for homebrew

- tui/keys.go
- tui/keys_test.go
Handle `h` and `l` keys for navigation within confirmation modal in empty/delete operation
Closes #232
> feat: handle vim-style navigation in confirmation

- .github/workflows/winget.yml
Winget Releaser now supports non-Windows runners, and `ubuntu-latest` is generally faster.
> ci: Change Winget Releaser job to `ubuntu-latest`

- tui/actions.go
- tui/tui.go
> fix: Enter key properly working when reading analysis from file

- .github/workflows/docker.yml
- Dockerfile
- INSTALL.md
- Makefile
- README.md
Containerizing gdu makes it easier to use without installing it.
Please note that I haven't tested the commands in the makefile, only executed them manually in the terminal
> feat: package gdu in docker container

- tui/actions_test.go
- tui/tui.go
> fix: check if type matches for selected device

- cmd/gdu/app/app.go
- cmd/gdu/main.go
- tui/keys_test.go
- tui/show.go
- tui/tui.go
- tui/tui_test.go
The user feedback is displayed in the header, I tried to make so that it disappears automatically after some time, but it seems to only update after some other action like moving in the list
Please let me know if this is good enough or if some other approach is preferred
Resolves #224.
> feat: add --no-delete option, resolves #224

- .tool-versions
- cmd/gdu/app/app.go
- cmd/gdu/app/app_test.go
- internal/testanalyze/analyze.go
- tui/actions.go
- tui/background.go
- tui/marked.go
- tui/status.go
- tui/tui.go
- tui/tui_test.go
> feat: delete/empty items in background

- README.md
- cmd/gdu/app/app.go
- internal/testanalyze/analyze.go
- pkg/analyze/file.go
- pkg/analyze/file_test.go
- pkg/analyze/stored.go
- pkg/remove/parallel.go
- pkg/remove/parallel_linux_test.go
- pkg/remove/parallel_test.go
- pkg/remove/remove.go
- pkg/remove/remove_linux_test.go
- pkg/remove/remove_test.go
- tui/tui.go
- tui/tui_test.go
> feat: delete directory items in parallel

- tui/format.go
- tui/format_test.go
- tui/keys.go
- tui/keys_test.go
- tui/show.go
- tui/tui.go
- tui/tui_test.go
> feat: ignore item

- README.md
- cmd/gdu/app/app.go
- cmd/gdu/main.go
- gdu.1.md
- tui/tui.go
- tui/tui_test.go
> feat: add --show-mtime (-M) option

- cmd/gdu/app/app.go
- cmd/gdu/app/app_test.go
- cmd/gdu/main.go
- stdout/stdout.go
- stdout/stdout_test.go
> feat: add option `--no-unicode` to disable unicode symbols

- go.mod
- go.sum
- tui/actions.go
- tui/show_file.go
- tui/show_file_test.go
> feat: support for reading gzip, bzip2 and xz files

- INSTALL.md
I tried to install gdu on windows, and got stuck after installation, because I needed to restart my terminal for Windows to handle gdu PATH.
I propose to add a single line that might help future Windows users.
> Update INSTALL.md: reminder to restart windows terminal

- README.md
- cmd/gdu/app/app.go
- cmd/gdu/main.go
- gdu.1.md
- pkg/analyze/top.go
- pkg/analyze/top_test.go
- stdout/stdout.go
- stdout/stdout_linux_test.go
- stdout/stdout_test.go
> feat: show top largest files

- .github/workflows/test.yml
- .tool-versions
- cmd/gdu/app/app.go
- cmd/gdu/app/app_test.go
- cmd/gdu/main.go
- go.mod
- stdout/stdout.go
- tui/actions.go
- tui/format.go
- tui/show.go
- tui/tui.go
- tui/tui_test.go
- tui/utils.go
> feat: introduce more style options 

- README.md
- gdu.spec
- internal/common/ignore.go
- pkg/analyze/file.go
- pkg/path/path.go
- stdout/stdout.go
- tui/actions.go
- tui/show_file.go
- tui/tui.go
found via `codespell -H` and `typos --hidden --format brief`
> docs: fix typos

- cmd/gdu/app/app.go
- cmd/gdu/app/app_test.go
- cmd/gdu/main.go
- internal/common/analyze.go
- internal/common/ui.go
- internal/common/ui_test.go
- internal/testanalyze/analyze.go
- pkg/analyze/dir_test.go
- pkg/analyze/parallel.go
- pkg/analyze/sequential.go
- pkg/analyze/stored.go
- pkg/analyze/symlink.go
- pkg/analyze/symlink_test.go
- pkg/annex/annex.go
- pkg/annex/annex_test.go
git-annex encodes the apparent size of files their symlinks.
gdu now is capable of extracting those sizes from the broken symlinks to calculate the total size of git-annex repositories.
Reference: https://git-annex.branchable.com/internals/key_format/
**Note:** real usage remains zero. gdu needs to be invoked via:
```shell
gdu --follow-symlinks --show-apparent-size --show-annexed-size
```
> feat: Add support showing size of absent git-annex'ed files

- .tool-versions
- tui/format.go
This is a fix for issue #412 where `gdu --show-item-count` incorrectly includes the directory itself in its item count.
> fix: item count for --show-item-count

- .gitignore
- README.md
- cmd/gdu/app/app.go
- cmd/gdu/main.go
- configuration.md
- stdout/stdout.go
- stdout/stdout_linux_test.go
- stdout/stdout_test.go
This PR implements a `--reverse-sort` command-line flag that reverses the default sorting order in non-interactive mode, displaying files from smallest to largest instead of largest to smallest.
**Fixes #435**
In non-interactive mode, gdu sorts entries from largest to smallest by default. When analyzing directories with many files, users must scroll through large files to view smaller ones, creating a poor user experience especially in terminal environments with limited screen space.
Added `--reverse-sort` flag that:
- Works exclusively in non-interactive mode
- Reverses sort order to show smallest files first  
- Maintains all existing functionality and performance
- Integrates with existing flags (`--summarize`, `--top`, etc.)
- Supports YAML configuration files
1. **CLI Interface**: …
> feat: Add --reverse-sort flag for non-interactive mode
